# This is a basic workflow that is manually triggered

name: PortalRestAPIFunctionalTests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        type: String
        description: Cognity Branch or revision or tag to run tests from
        default: 'master'
        required: true
      serverURL:
        type: choice
        description: AWS POSTGRE TESTS:http://api-testing.postgre-eu-central-1-stats-tests.analytics.rse.dev.eu-central-1.aws.fdscloud.io:8080/WebPortal/rest/
        options: 
        - proba1
        - test2
        - test3
        - test4
        - test5
        - test6
        - test7
        - test8
        - test9
        - test10
        required: true
      user:  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: [ self-hosted, ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Build with Ant
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          echo $GITHUB_TOKEN

