# This is a basic workflow that is manually triggered

name: PortalRestAPIFunctionalTests
on: 
  workflow_dispatch:
    inputs:
      serverURL:
        type: choice
        options: 
        - proba1
        - test2
        - test3
        - test4
        - test5
        - test6
        - test7
        - test8
        - test9
        - test10
        required: true
      user:  
        type: String
        default: Iweto
        required: true
      password:
        type: String
        required: true
      asOfDate:
        type: choice
        required: true
        options:
        - latestQuarterEnd
        - latestMonthEnd
        - "2021-12-31"
        - "2019-09-30"
      benchmarkId:
        type: choice
        default: Portal_SP50-USD_TR
        required: true
        options:
        - "Portal_SP50-USD_TR" 
      groups:
        type: String
        default: DEV
        required: true
      folder:
        type: choice
        required: true
        options:
        - DEV
        - DEKA
        - HARTFORD
        - CAPGROUP 
      fixedAsOfDate:
        type: choice
        required: true
        options:
        - "2021-12-31"
        - "2018-09-30"
      verifyValues:  
        type: boolean
        required: true
        default: true     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Build with Ant
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          serverURL: ${{ github.event.inputs.serverURL }}
          user: ${{ github.event.inputs.user }}
          password: ${{ github.event.inputs.password }}
          asOfDate: ${{ github.event.inputs.asOfDate }}
          benchmarkId: ${{ github.event.inputs.benchmarkId }}
          groups: ${{ github.event.inputs.groups }}
          folder: ${{ github.event.inputs.folder }}
          fixedAsOfDate: ${{ github.event.inputs.fixedAsOfDate }}
          verifyValues: ${{ github.event.inputs.verifyValues }}
      run: 
          echo $GITHUB_TOKEN
          echo $serverURL
          echo $user
          echo $password
          echo $asOfDate
          echo $benchmarkId
          echo $groups
          echo $folder
          echo $fixedAsOfDate
          echo $verifyValues 
